server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.93.134
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code: 8ac732670c5c4565b1965deca9401ffc
    host: https://gyytz.market.alicloudapi.com
    method: POST
    path: /sms/smsSend
    sign: hw157280
    skin: 84683
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000